# Applikations navn og profil
spring.application.name=Turistguide

# Database forbindelse (H2 i hukommelsen)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# SQL Indstillinger (Vigtigt for at 'schema.sql' virker)
spring.sql.init.mode=always

# H2 Console (så du kan se data på http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.sql.init.schema-locations=classpath:db/schema.sql
spring.sql.init.data-locations=classpath:db/data.sql

