# Database forbindelse til rigtig database (f.eks. MySQL/Postgres)
spring.datasource.url=${PROD_DATABASE_URL}
spring.datasource.username=${PROD_USERNAME}
spring.datasource.password=${PROD_PASSWORD}

# Ingen H2 konsol i produktion!
spring.h2.console.enabled=false

# Vi vil typisk IKKE køre scripts automatisk i produktion
spring.sql.init.mode=never